import type { Metadata } from "next";
import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Footer";
import { SessionProvider } from "next-auth/react";
import Navbar from "./components/Navbar";
// import { NextIntlClientProvider } from "next-intl";
// import { getMessages } from "next-intl/server";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


interface RootLayoutProps {
  children: React.ReactNode;
  // params: {
  //   locale: string
  // };
}
export default async function RootLayout({
  children,
  // params: { locale },
}: Readonly<RootLayoutProps>) {

  // const messages = await getMessages(locale)
  // const messages = await getMessages();

  return (
    <html lang='eng'>
      <body
        className={`${outfit.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Navbar />
          <main className="">
            {/* <NextIntlClientProvider messages={messages}> */}
            {children}
            {/* </NextIntlClientProvider> */}
          </main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
